return {
  -- "AstroNvim/astrolsp",
  -- -- https://github.com/lasorda/protobuf-language-server
  -- ---@type AstroLSPOpts
  -- opts = function(plugin, opts)
  --   --   --   -- insert "prolog_lsp" into our list of servers
  --   opts.servers = opts.servers or {}
  --   table.insert(opts.servers, "pls")
  --
  --   opts.config = require("astrocore").extend_tbl(opts.config or {}, {
  --     --   -- this must be a function to get access to the `lspconfig` module
  --     pls = {
  --       cmd = { "pls" },
  --       filetypes = { "proto", "cpp" },
  --       root_dir = require("lspconfig.util").root_pattern ".git",
  --       single_file_support = true,
  --       settings = {
  --         ["additional-proto-dirs"] = {
  --           -- path to additional protobuf directories
  --           "vendor",
  --           -- "third_party",
  --         },
  --       },
  --     },
  --   })
  -- end,
}
